repos:
-   repo: local
    hooks:
    -   id: lint-all
        name: Run all linters
        entry: ./scripts/pre_commit_lint.sh
        language: system
        pass_filenames: false
        # stages: [pre-commit]  # Commented out to disable pre-commit hook 